- name: Criando o Security Group
  local_action:
    module: ec2_group
    name: "{{ sec_group_name }}"
    description: sg iac
    profile: "{{ profile }}"
    region: eu-central-1
    rules:
    - proto: tcp
      from_port: 22
      to_port: 22
      cidr_ip: 10.0.0.0/8
      rule_desc: SSH
    rules_egress:
    - proto: all
      cidr_ip: 0.0.0.0/8
  register: basic_firewall
  
