- name: Criando o diretorio da app Ansible
  file: path={{item}} state=directory
  with_items:
    - /opt/ansible
    - /opt/amsible/logs
    - /opt/ansible/conf
  register: criando_diretorios

- name: Copiando o arquivo de deployment da app para o host
  template:
    src: app-v1.yml.j2
    dest: /opt/ansible/app-v1.yml
    owner: root
    group: root
    mode: 0644
  register: copiando_template
    
- name: Copiando o arquivo de service da app para o host
  copy: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - { src: 'service_app.yml', dest: '/opt/ansible/service_app.yml' }
  register: copiando_service_file

- name: Criando o deployment do app
  shell: kubectl apply -f /opt/ansible/app-v1.yml
  register: deploy_app

- name: Criando o Service do app
  shell: kubectl apply -f /opt/ansible/service_app.yml
  register: deploy_svc_app
